GET https://fs-phonebook-backend.glitch.me/api/persons HTTP/1.1

###

POST https://fs-phonebook-backend.glitch.me/api/persons HTTP/1.1
content-type: application/json

{
    "name": "Name",
    "number": "123"
}

###

DELETE https://fs-phonebook-backend.glitch.me/api/persons/9560 HTTP/1.1

#
##
###
# Local
###
##
#

GET http://localhost:3001/api/persons HTTP/1.1

###

POST http://localhost:3001/api/persons HTTP/1.1
content-type: application/json

{
    "name": "Senku2",
    "number": "1236778"
}

###

DELETE http://localhost:3001/api/persons/668aaf679b6b6f9ef1619016 HTTP/1.1
